### ISSUE TITLE
Unhandled Exception - Index was outside the bounds of the array

### ISSUE THREAD

**Issue by Acidham** [harborsiem/SolvisSC2Viewer#1]
When I try to open Solvis  log files with SC2 Viewer I am receiving the following error. .NET 4.8 is installed on Windows 10. 

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at SolvisSC2Viewer.RowValues.LogInfos.SetNextLogInfo(String row, Int32 lineNumber)
   at SolvisSC2Viewer.RowValues..ctor(String row, Int32 lineNumber)
   at SolvisSC2Viewer.DataManager.FillSolvisList(String fileName)
   at SolvisSC2Viewer.OpenFileAction.Execute(ActionData data)
   at SolvisSC2Viewer.Action.Process(ActionData data)
   at SolvisSC2Viewer.Action.ProcessEvent(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4075.0 built by: NET48REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
SolvisSC2Viewer
    Assembly Version: 1.0.0.0
    Win32 Version: 2.1.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Solvis/SolvisSC2/SolvisSC2Viewer.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4042.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Windows.Forms.DataVisualization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3815.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.DataVisualization/v4.0_4.0.0.0__31bf3856ad364e35/System.Windows.Forms.DataVisualization.dll
----------------------------------------
pqi4rrvg
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


```

**Comment by harborsiem** [comment]
@Acidham , Sorry about late response.
Please can you send a solvis log file where this issue happens. Please tell me the version of your Solvis control and the version you put in the configuration. You can also send the file User.config from C:\Users\Your account\AppData\Roaming\Solvis\SolvisViewer.

**Comment by Acidham** [comment]
I tried to get SolvisControl version from System Information but not sure where I can find it. 
All settings in SolvisViewer are set to default. 

Attached following files:
* logifle: [mi210322.txt](https://github.com/harborsiem/SolvisSC2Viewer/files/6682077/mi210322.txt)
* config file: [User.config.txt](https://github.com/harborsiem/SolvisSC2Viewer/files/6682079/User.config.txt)
* screenshot of Solvis Control - System Information: 
![IMG_2508](https://user-images.githubusercontent.com/17712121/122670000-0bfd2e80-d1c0-11eb-927a-4a5d4cc9b9d3.png)

**Comment by harborsiem** [comment]
@Acidham , I have build a new version 2.1.2. The version of SolvisControl you can see in the "System Informationen" picture; last row on the left side (MA205.06 N300).
For selecting the mi*.txt logfiles as default in the Open dialog it will be a good idea to set the configuration for the version to a value of 132. (Extras -> Konfiguration -> Sonstiges)

**Comment by Acidham** [comment]
@harborsiem works with the new version. I could not change configuration. When I change via Extras > Configuration > Sonstiges, change value to 132, click OK and open the Editor again the value is still 131. User.config also shows 131. Bug again I can see graphs now and I am not sure if this is another issue. Let me know and I create a new issue for that.

**Comment by harborsiem** [comment]
@Acidham , The Application stores values in User.config only when the application is closing. After application closing the Editor show me the new value.

**Comment by Acidham** [comment]
@harborsiem For me the value cannot be stored. 

1. I changed value to 132 
2. closed Solvis Viewer and reopened SV
3. Value is still 131

I delete user.config to avoid permission issues
1. opened SV > user.config was created
2. changed value from 131 to 132
3. closed SV and reopened SV
4. Value is still 131

When I edit user.config manually from 131 to 132 the config editor shows 132.

**Comment by harborsiem** [comment]
@Acidham : In the new version 2.1.3 changing of SolvisControl version is now OK

**Comment by Acidham** [comment]
@harborsiem now it works! Thank you for the quick turn around!
